# Generated by Django 4.1.5 on 2023-02-18 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.BooleanField(default=True)),
                ('sub', models.BooleanField(default=True)),
                ('mul', models.BooleanField(default=True)),
                ('div', models.BooleanField(default=True)),
                ('duration', models.PositiveIntegerField(default=120)),
                ('add_left_min', models.PositiveIntegerField(default=2)),
                ('add_left_max', models.PositiveIntegerField(default=100)),
                ('add_right_min', models.PositiveIntegerField(default=2)),
                ('add_right_max', models.PositiveIntegerField(default=100)),
                ('mul_left_min', models.PositiveIntegerField(default=2)),
                ('mul_left_max', models.PositiveIntegerField(default=12)),
                ('mul_right_min', models.PositiveIntegerField(default=2)),
                ('mul_right_max', models.PositiveIntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('attempted', models.DateTimeField(auto_now_add=True)),
                ('ques', models.JSONField()),
                ('params', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
